In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('/content/01Exercise1.csv')

In [4]:
df=data.copy()

In [6]:
df.head()

gender married   ch  income  loanamt status
0   Male      No  1.0    5849      NaN      Y
1   Male     Yes  1.0    4583    128.0      N
2   Male     Yes  1.0    3000     66.0      Y
3   Male     Yes  1.0    2583    120.0      Y
4   Male      No  1.0    6000    141.0      Y

In [7]:
df.isnull().sum()

gender     13
married     3
ch         50
income      0
loanamt    22
status      0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

gender     0
married    0
ch         0
income     0
loanamt    0
status     0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 529 entries, 1 to 613
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   gender   529 non-null    object 
 1   married  529 non-null    object 
 2   ch       529 non-null    float64
 3   income   529 non-null    int64  
 4   loanamt  529 non-null    float64
 5   status   529 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 28.9+ KB


In [11]:
df.drop('gender',axis=1,inplace=True)

In [12]:
df['ch']=df['ch'].astype('category')

In [13]:
df=pd.get_dummies(df,drop_first=True)

In [14]:
df.head()

income  loanamt  married_Yes  ch_1.0  status_Y
1    4583    128.0            1       1         0
2    3000     66.0            1       1         1
3    2583    120.0            1       1         1
4    6000    141.0            0       1         1
5    5417    267.0            1       1         1

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [16]:
df['income']=scaler.fit_transform(df[['income']])

In [17]:
df['loanamt']=scaler.fit_transform(df[['loanamt']])


In [18]:
df.head()

income   loanamt  married_Yes  ch_1.0  status_Y
1 -0.128073 -0.194250            1       1         0
2 -0.392077 -0.971015            1       1         1
3 -0.461621 -0.294478            1       1         1
4  0.108246 -0.031380            0       1         1
5  0.011017  1.547205            1       1         1

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [21]:
x

income   loanamt  married_Yes  ch_1.0
1   -0.128073 -0.194250            1       1
2   -0.392077 -0.971015            1       1
3   -0.461621 -0.294478            1       1
4    0.108246 -0.031380            0       1
5    0.011017  1.547205            1       1
..        ...       ...          ...     ...
609 -0.408754 -0.908372            0       1
610 -0.207624 -1.296754            1       1
611  0.453802  1.371807            1       1
612  0.372249  0.544929            1       1
613 -0.128073 -0.131608            0       0

[529 rows x 4 columns]

In [22]:
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: status_Y, Length: 529, dtype: uint8

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1234,stratify=y)

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr=LogisticRegression()

In [26]:
lr.fit(x_train,y_train)

LogisticRegression()

In [27]:
y_pred=lr.predict(x_test)

In [28]:
y_pred

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1], dtype=uint8)

In [30]:
np.array(y_test)

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1], dtype=uint8)

In [31]:
from sklearn.metrics import confusion_matrix

In [33]:
cm=confusion_matrix(y_test,y_pred)

In [34]:
cm

array([[ 29,  20],
       [  2, 108]])

In [35]:
lr.score(x_test,y_test)

0.8616352201257862